# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /workspace

# Install necessary dependencies for your package
RUN python -m pip install --upgrade pip

# Install another dependencies
RUN pip install -U -i https://test.pypi.org/simple/ alexnet --extra-index-url https://pypi.org/simple/

# Set default command for the container
CMD ["bash"]
