FROM pytorch/pytorch

ENV PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install pytest
RUN pip install --upgrade pip
RUN pip install jupyterlab notebook

WORKDIR /workspace
COPY . .
RUN pip install .

EXPOSE 8888

CMD ["bash"]
