name: Publish to TestPyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install build and twine packages
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Verify that requirements.txt exists (Optional)
      - name: Verify requirements.txt
        run: ls -l requirements.txt

      # Build the distribution files (source and wheel)
      - name: Build the package
        run: python -m build

      # Upload the package to TestPyPI
      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m twine upload --repository testpypi dist/*
